services:
  api-gateway:
    image: ${DOCKER_IMAGE}:IMAGE_TAG_PLACEHOLDER
    container_name: ${APIGATEWAY_NAME}
    ports:
      - "${APIGATEWAY_PORT}:${APIGATEWAY_PORT}"   # 외부 8080 -> 내부 8080
    env_file:
      - .env
    networks:
      - mumulbo-network
    depends_on:
      - redis-ratelimit
    restart: no
    logging:
        driver: fluentd
        options:
            fluentd-address: localhost:24224
            tag: mmb-apigateway
  redis-ratelimit:
    image: redis:7
    container_name: ${APIGATEWAY_NAME}-redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: ["redis-server", "--port", "6381"]
    env_file:
      - .env
    networks:
      - mumulbo-network

networks:
  mumulbo-network:
    external: true
    driver: bridge
    name: ${MMB_DOCKER_NETWORK}
